Controllers films users
SnezhanaB/java-filmorate pull request #5
Opened 2024-01-05 19:49 UTC by SnezhanaB

2024-01-06 14:42 UTC, kriwsha requested changes

2024-01-06 14:42 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/model/NotFoundException.java
> +public class NotFoundException extends Exception {
Исключения я бы рекомендовал вынести в отдельный пакет. Модель - это некий осязаемый объект, с которым вы работаете (в вашем случае это пользователь и фильм). Исключение - это вспомогательный инструмент. Смешивать эти классы - плохая практика.

2024-01-06 14:42 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/model/ValidationException.java
> +public class ValidationException extends Exception {
Это исключение тоже рекомендую вынести

2024-01-06 14:42 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate BIRSDAY_OF_CINEMA = LocalDate.of(1895, 12, 28);
Не могу пройти мимо - bir**th**day

2024-01-06 14:42 UTC, kriwsha commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(BIRSDAY_OF_CINEMA)) {
Я бы рекомендовал валидацию (как для фильмов, так и для пользователей) вынести в отдельный утильный класс. Плюс такого подхода в том, что при чтении кода вы видите, что сначала происходит валидация (не важно, как она происходит - это можно понять потом), а потом уже непосредственно логика. Но если валидация не вынесена, то приходится искать, где начинается непосредственно бизнес-логика приложения.

2024-01-08 11:50 UTC, SnezhanaB commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(BIRSDAY_OF_CINEMA)) {
Реализовала с помощью Constraint'ов

2024-01-09 11:20 UTC, kriwsha approved these changes

2024-01-09 14:59 UTC, merged